version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
arts_and_crafts = true
smart_observer = true
everycomp = true
spelunkers_charm = true
farmersdelight = true
darkerdepths = true
nomansland = true
alexsmobs = true
gladius = true
weeping_angels = true
concoction = true
abundant_atmosphere = true
recharged = true
etched = true
quark = true
easyanvils = true
sub_expansion = true
fiberopticcables = true
additionalplacements = true
repairstation = true
citadel = true
abyssal_decor = true
yeastnfeast = true
incision = true
additionaladditions = true
amendments = true
moonlight = true
snowrealmagic = true
heart_crystals = true
exposure = true
gravestones = true
doom_and_gloom = true
supplementaries = true
incubation = true
wind-charged-weaponry = true
redstonelantern = true
clutternomore = true
frame_changer = true
goldenhopper = true
yungscavebiomes = true
overgeared = true
mannequins = true
monstereggs = true
accents = true
minecraft = true
omphalos = true
spawn = true
digamma = true
creeperoverhaul = true
oreganized = true
blockus = true
