#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Sun Mar 15 23:45:27 GMT+04:00 2026
alwaysLogTamperWarnings=false
