charge_chamber.fire_charge_strength_modifier=1.0 #0.5 would be half of its current strength and 2 would be double | default: 1.0
charge_chamber.wind_charge_strength_modifier=1.0 #Same thing but wind charge so it's weird | default: 1.0
ominous_spawner.difficulty_modifier=0 #Negative values = easier, positive values = harder (only takes whole numbers so no 0.3141) | default: 0

