name = "MinecraftB2Setup"
author = "KateBulka"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d282ccebe8332de474bb72bc00797dbda3b9afff2c093e2048fc5e21d5646ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-versions = ["1.20.5", "1.20.6", "1.21", "1.21.1"]
datapack-folder = "data_packs"
