name = "MinecraftB2Setup"
author = "KateBulka"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e13bba7a261de9363ced70b270db7dc8680b9c90b1042851bb5563b385e218d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-versions = ["1.20.5", "1.20.6", "1.21", "1.21.1"]
datapack-folder = "data_packs"
