name = "MinecraftB2Setup"
author = "KateBulka"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93f72f1533a9432f1b110901b2e6ede1440960a697c554dccb8e0aaa6bf9f19f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-versions = ["1.20.5", "1.20.6", "1.21", "1.21.1"]
datapack-folder = "data_packs"
