StartupEvents.registry("block", (event) => {
    event.create("minecraft:spinel_ore")
    .soundType("amethyst")
    .mapColor("color_pink")
    .hardness(1.0)
    .resistance(3600000.0)
    .requiresTool(true)
    .tagItem('c:ores')
    .tagItem('c:ores_in_ground/stone')
    .tagBlock('minecraft:needs_wooden_tool')
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('c:ores')
    .tagBlock('c:ores_in_ground/stone')
    .tagBlock('minecraft:snaps_goat_horn')
    .lightLevel(1 / 15)

    event.create("frame_changer:obsidian")
    .mapColor("color_black")
    .soundType("stone")
    .hardness(50.0)
    .resistance(1200.0)
    .requiresTool(true)
    .tagBlock('overgeared:needs_steel_tool')
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:overworld_carver_replaceables')
    .tagBlock('oreganized:mineable/scribe')
    .tagBlock('oreganized:silktouch_using_scribe')
    .tagBlock('forge:obsidian')
    .tagBlock('frame_changer:portal_frames')
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('spelunkery:base_stone_end') 
    .tagBlock('spelunkery:spring_geyser_breakable')

    event.create("minecraft:rocky_dirt")
    .soundType("rooted_dirt")
    .mapColor("dirt")
    .hardness(1)
    .resistance(3)
    .tagItem('minecraft:dirt')
    .tagBlock('moss_replaceable')
    .tagBlock('lush_ground_replaceable')
    .tagBlock('enderman_holdable')
    .tagBlock('bamboo_plantable_on')
    .tagBlock('mineable/shovel')
    .tagBlock('mineable/pickaxe')
    .tagBlock('dirt')
    .tagBlock('sniffer_diggable_block')

    event.create("minecraft:cocytus")
    .unbreakable()
    .mapColor("ice")
    .slipperiness(0.98)
    .notSolid()
    .lightLevel(0.5)
    .defaultCutout()
    .noDrops()
    .waterlogged()
})