name = "MinecraftB2"
author = "KateBulka"
version = "1.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37ec59b5d573fb99cba92ec3413c92681ae17e9fb8a5f857d143097156438a4b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
unsup = "1.1.6"

[options]
acceptable-versions = ["1.20.5", "1.20.6", "1.21", "1.21.1"]
datapack-folder = "data_packs"
