name = "MinecraftB2"
author = "KateBulka"
version = "1.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d869e1cfb7e98c3c15eb6bc41a3d27c122a7e370de9ab7a40c8e184d78c1c453"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
unsup = "1.1.6"

[options]
acceptable-versions = ["1.20.5", "1.20.6", "1.21", "1.21.1"]
datapack-folder = "data_packs"
