# Don't change this! Version used to track needed updates.
version = 0
enableParticleCulling = false
particleRenderDistance = 5
particleCullingBlocklist = [  ]
cullParticlesInUnloadedChunks = false
allowUsingBlendedRenderType = false
spellParticlesUseBlendedRenderType = false
glowingLavaDrops = true
fluidDropsEvaporate = true
fluidDropsEvaporationVolume = 0.25
dropLandInFluidRipples = true
dropLandSoundVolume = 1.0
lavaSparkSmoke = false
sparksScale = 1.0
poppingHearts = false
poppingBubbles = true
poppingBubblesVolume = 0.0
glowingEnchantmentParticles = true
translucentEnchantmentParticles = true
disableRandomizedShading = true
potionParticleAlpha = 0.7
potionParticleAlphaNearPlayer = 0.2
leavesLandOnGround = false
leavesLandOnWater = false
leavesLandingOnWaterRipples = false
leavesLandingOnWaterKeepMomentum = false
fallenLeavesLifeTime = 20
rainIncreasesLeavesMovementSpeed = true
staticFlameBrightness = true
fireOverlayHeight = -0.15
fireOverlayAlpha = 0.9
fireOverlayAlphaWithFireResistance = 0.4
mobSkullShaders = true
nightVisionFading = true
nightVisionFadingTime = 100
enableEasterEggs = true