LootJS.modifiers(event => {
    const additions = [
        // LootEntry.of('gladius:golden_wand').when(c => c.randomChance(0.5)).matchBiome("#c:is_cold"),
        LootEntry.of('nomansland:resin').setCount([1, 3]).when(c => c.randomChance(0.75).matchDimension("minecraft:overworld")),
        LootEntry.of('nomansland:resin').setCount([1, 5]).when(c => c.randomChance(0.75)).matchBiome("#c:is_cold").matchDimension("minecraft:overworld"),
        LootEntry.of('darts:dart').setCount([1, 5]).when(c => c.randomChance(0.75)),
        LootEntry.of('darts:dart').setCount([1, 5]).when(c => c.randomChance(0.75)).matchBiome("#c:is_hot"),
        LootEntry.of('minecraft:arrow').setCount([1, 8]).when(c => c.randomChance(0.25)),
        LootEntry.of('nomansland:incendiary_arrow').setCount([1, 8]).when(c => c.randomChance(0.25)).matchDimension("minecraft:the_nether"),

        LootEntry.of('accents:sombrero').when(c => c.randomChance(0.25)).matchBiome("#c:is_hot"),    
        LootEntry.of('accents:cowboy_hat').when(c => c.randomChance(0.25)).matchBiome("#c:is_hot"),    
        LootEntry.of('accents:christmas_hat').when(c => c.randomChance(0.25)).matchBiome("#c:is_cold"),    
        LootEntry.of('accents:captain_hat').when(c => c.randomChance(0.25)).matchBiome("#c:is_aquatic"), 
        LootEntry.of('accents:pirate_hat').when(c => c.randomChance(0.25)).matchBiome("#c:is_aquatic"),   

        LootEntry.of('accents:top_hat').when(c => c.randomChance(0.25)),   
        LootEntry.of('accents:overtop_hat').when(c => c.randomChance(0.25)),   
        LootEntry.of('accents:pickelhaube').when(c => c.randomChance(0.25)).matchBiome("#c:is_cave"),   

        LootEntry.of('minecraft:lead').setCount([1, 2]).when(c => c.randomChance(0.2)),
    ]

    const all_paintings = [
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:accident"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:alban"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:alpha"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:aztec"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:aztec2"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:beta"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:bomb"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:bubbles"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:crusty"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"incubation:egg"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:euphoria"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:guardian_angel"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:kebab"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:meditative"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:mouse_on_venus"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:perennial"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:plant"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:still_life"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:tussie_mussie"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:wasteland"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:wrong_side"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:bliss"}]', 
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:bouquet_edition"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:cat"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:film"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:flowers"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:graham"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:iconography"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:jazz_town"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:meaningless"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:painting"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:prairie_ride"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:rising_sun_and_fading_death"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:rosemalling"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:self_reflection"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:squid_games"}]',

        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:stare"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:vice"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:wanderer"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:blossoms"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:courbet"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:creebet"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:eyes"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:medley"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:pool"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:post_mortem"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:rainforest"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:red_dawn"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:sea"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:sunrise_sparse"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:sunset"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:the_sun_has_set"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:wildstyle"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:afternoon"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:farlander"}]', 
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:final_bloom"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:fox"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:greatsword"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:luminescent"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:pillars"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:sandstones"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:shapes"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:stalks"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:sunflower"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:underwater"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:boscage"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:brick_monster"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:eye"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:gears"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:screaming"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:you_have_been_trolled"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:heavens_ladder"}]',

        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:prickle"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:table"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:alpha"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:aquaculture"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:baroque"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"supplementaries:bombs"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:bust"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:fights_on_the_underwater_heights"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:generator"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"heart_crystals:heartbeat"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:lotl"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:macabre"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:macabre_alt"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:macrocosm"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:match"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:operator"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:parrot"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:skull_and_roses"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:stage"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:traveller"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:void"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:watching"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:waves"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:winter_wonderland"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:wither"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:beachside"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:drippy"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:heirloom"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:mountains"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:an_intruder"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:best_friend"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:cult"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:distant_peaks"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:harvest_moon"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:heartcore"}]',

        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:moonlight_tower"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:morning_on_the_seine"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:mourned_demise"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:ocean"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:pixel_gobelin"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:pools"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:rana"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:randomtickspeed"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:shattered_dream"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:taiga"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:time_flies"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:void_manor"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:warden_of_the_bloodmoon"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:wardona_lisa"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:yonder"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:ancestor"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:creepy"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:ending"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:nyctinasty"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:pyramid"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:slime_chunk"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:unwrap"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:we_need_to_go_deeper"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:windmill_field"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:awful_housing"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:caricature"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:cherry_moon"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:escapeless"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:gulls"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:serpent"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:changing"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:fighters"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:finding"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:inbetweenlands"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:lowmist"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:never_blooming_wattle"}]',

        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:passage"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:picturesque"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:the_painting_at_end_of_catalogue"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:anchor"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:bouquet"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:cavebird"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:cotan"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:death"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:dennis"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:endboss"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:endy_warhol"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:fern"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:life_cycle"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:mode_creative"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:owlemons"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:sunflowers"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:tides"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:waves"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:yondering_cranium"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:backyard"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:oak_door"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:pond"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:the_scream"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:donkey_kong"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:feather_falling"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:rainbows"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:rainbows_alt"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:rainbows_trans"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:skeleton"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:statue"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:storm"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:the_far_lands"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:virtuosi_pas_de_deux"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:burning_skull"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:cloth"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:cloud_cuckoo"}]',

        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"incubation:culprit"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:giant"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:justice"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:orb"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:pigscene"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:pointer"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"portfolio:stair_hall"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"minecraft:unpacked"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:the_tree_of_life"}]',
        'minecraft:painting[entity_data={id:"minecraft:painting",variant:"slimes_gallery:kitty"}]'
    ]
    
    const paintings = {
        "#c:is_cave": [

        ],

        "#c:is_aquatic": [
            
        ]
    }

    event.addTableModifier(/.*chests.*/).pool(pool => {
        additions.forEach(entry => {
            pool.addEntry(entry)
        })

        for (const biome_id in paintings) {
            paintings[biome_id].forEach(entry => {
                pool.addEntry(LootEntry.of(entry).matchBiome(biome_id).when(c => c.randomChance(0.75)))
                // pool.addEntry(LootEntry.of(entry).matchBiome(biome_id))
            })
        }
    })

    event.addBlockModifier("#minecraft:leaves")
    .addLoot(
        LootEntry.of('nomansland:resin').randomChance(0.1)
        .when(c => {
            c.matchTool(
                ItemFilter.custom(tool => tool == null || (!tool.is("minecraft:shears") && !tool.hasEnchantment("silk_touch", 1)))
            )
        })
    )
})